layout_spectrum: 0.4681694
typography_spectrum: 0.09172581
color:
  saturation: 0.8568226
  lightness: 0.0284217
  brandStrength: 0.2233932
  rhythmicContrast: 0.369645
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
name: Harshitha
